site_name: 'Andre''s Blog'
site_description: 'My personal Blog!'
site_author: 'Andre_601'
site_url: 'https://www.andre601.ch/blog'

copyright: |
  &copy; Andre_601

docs_dir: docs/

repo_name: Andre601/blog
repo_url: https://github.com/Andre601/blog

theme:
  name: 'material'
  custom_dir: 'theme'
  favicon: 'assets/img/icon.jpg'
  logo: 'assets/img/icon.jpg'
  icon:
    repo: octicons/repo-24
    tag:
      mc: material/cube
      spigot: fontawesome/solid/faucet-drip
      paypal: fontawesome/brands/paypal
      java: fontawesome/brands/java
      discord: fontawesome/brands/discord
      mastodon: fontawesome/brands/mastodon
      twitter: fontawesome/brands/twitter
  palette:
    scheme: 'slate'
    primary: 'grey'
    accent: 'blue'
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - content.code.annotate

extra_css:
- assets/css/extra.css

extra_javascript:
- assets/js/timeago.min.js
- assets/js/timeago_mkdocs_material.js

watch:
  - theme

extra:
  social:
    - icon: 'simple/github'
      link: 'https://github.com/Andre601'
    - icon: 'fontawesome/solid/house'
      link: 'https://andre601.ch'
    - icon: 'simple/mastodon'
      link: 'https://blobfox.coffee/@andre_601'
  tags:
    Minecraft: mc
    SpigotMC: spigot
    PayPal: paypal
    Java: java
    Discord: discord
    Mastodon: mastodon
    Twitter: twitter

nav:
  - Home: index.md
  - Tags: tags.md

plugins:
  - search
  #- awesome-pages # Doesn't seem to be supported by the blog plugin (yet)
  - blog:
      blog_dir: .
      post_url_date_format: yyyy
      archive: false
      pagination_template: "$link_first $link_previous ~2~ $link_next $link_last"
      draft_if_future_date: true
  - tags:
      tags_file: tags.md
  - git-revision-date-localized:
      type: custom
      timezone: Europe/Zurich
      locale: en
      custom_format: '%d. %B %Y'
      exclude:
        - index.md
        - posts/index.md
        - posts/tags.md
        - reviews/index.md
        - reviews/apply.md
        - reviews/tags.md
  - glightbox

markdown_extensions:
  - markdown.extensions.meta:
  - markdown.extensions.attr_list:
  - markdown.extensions.footnotes:
      PLACE_MARKER: "<!-- Footnotes -->"
  - markdown.extensions.admonition:
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.details:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
  - pymdownx.magiclink:
  - pymdownx.smartsymbols:
  - pymdownx.snippets:
      base_path: 'theme/snippets'
  - pymdownx.superfences:
  - pymdownx.tilde:
