site_name: 'Andre''s Blog'
site_description: 'My personal Blog!'
site_author: 'Andre_601'
site_url: 'https://www.andre601.ch/blog'

copyright: |
  &copy; Andre_601

docs_dir: docs/

repo_name: Andre601/blog
repo_url: https://github.com/Andre601/blog

theme:
  name: 'material'
  custom_dir: 'theme'
  favicon: 'assets/img/icon.jpg'
  logo: 'assets/img/icon.jpg'
  icon:
    repo: octicons/repo-24
  palette:
    scheme: 'slate'
    primary: 'grey'
    accent: 'blue'
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - content.code.annotate

extra_css:
- assets/css/extra.css

extra_javascript:
- assets/js/timeago.min.js
- assets/js/timeago_mkdocs_material.js

extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/Andre601'
    - icon: 'fontawesome/solid/house'
      link: 'https://andre601.ch'


plugins:
  - search
  - awesome-pages
  - redirects:
      redirect_maps:
        'posts/in-defense-of-spigotmc.md': 'posts/2020/12-20-in-defense-of-spigotmc.md'
        'posts/truth-and-lies.md': 'posts/2020/12-24-truth-and-lies.md'
        'posts/pros-and-cons-of-spigot.md': 'posts/2021/02-07-pros-and-cons-of-spigot.md'
        'jda-utils-alternatives.md': 'posts/2021/06-13-jda-utilities-alternatives.md'
  - blogging:
      dirs:
        - posts/2020
        - posts/2021
        - posts/2022
      features:
        tags:
          index_page: 'posts/tags.md'
          insert: top
      categories:
        - name: reviews
          dirs:
            - reviews/2022
          fatures:
            tags:
              index_page: 'reviews/tags.md'
              insert: top
          template: 'theme/blog/blog-override.html'
          theme:
            name: card
          locale: de
          size: 5
          time_format: '%d.%m.%Y'
          meta_time_format: '%d.%m.%Y'
      template: 'theme/blog/blog-override.html'
      theme:
        name: card
      locale: de
      size: 5
      time_format: '%d.%m.%Y'
      meta_time_format: '%d.%m.%Y'
  - git-revision-date-localized:
      type: custom
      timezone: Europe/Zurich
      locale: en
      custom_format: '%d. %B %Y'
      exclude:
        - index.md
        - posts/index.md
        - posts/tags.md
        - reviews/index.md
        - reviews/apply.md
        - reviews/tags.md

markdown_extensions:
  - markdown.extensions.meta:
  - markdown.extensions.attr_list:
  - markdown.extensions.footnotes:
      PLACE_MARKER: "<!-- Footnotes -->"
  - markdown.extensions.admonition:
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.details:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
  - pymdownx.magiclink:
  - pymdownx.smartsymbols:
  - pymdownx.snippets:
      base_path: 'theme/snippets'
  - pymdownx.superfences:
  - pymdownx.tilde:
